
PLATFORM ?= dromajo_cosim

ifeq ($(PLATFORM),dromajo_cosim)
PLATFORM_DRAM_BASE ?= 0x80000000
PLATFORM_SP        ?= 0x8F000000
else ifeq ($(PLATFORM),zynqparrot)
PLATFORM_DRAM_BASE ?= 0x80000000
PLATFORM_SP        ?= 0x877FF000
else ifeq ($(PLATFORM),vcu128)
PLATFORM_DRAM_BASE ?= 0x80000000
PLATFORM_SP        ?= 0xF0000000
else
$(error "PLATFORM not found")
endif

